export const ROLES = {
  FLEET_MANAGER: "fleet_manager",
  DRIVER: "driver",
  SAFETY_OFFICER: "safety_officer",
  FINANCIAL_OFFICER: "financial_officer",
  TRIP_DISPATCHER: "trip_dispatcher",
};

export const ALL_ROLES = Object.values(ROLES);


export const PERMISSIONS = {
  MANAGE_VEHICLES: [ROLES.FLEET_MANAGER],
  MANAGE_DRIVERS: [ROLES.FLEET_MANAGER, ROLES.SAFETY_OFFICER],
  MANAGE_TRIPS: [ROLES.FLEET_MANAGER, ROLES.TRIP_DISPATCHER],
  MANAGE_MAINTENANCE: [ROLES.FLEET_MANAGER, ROLES.SAFETY_OFFICER],
  MANAGE_FUEL_EXPENSES: [ROLES.FLEET_MANAGER, ROLES.FINANCIAL_OFFICER],
};
